Repository leonidas97/kts-nwt, pull requests merged in 2020-02, with the labels that each got.

#90 Fixed manifestation view bug when not logged in and added few methods for section editing purposes
  backend/code/m-booking/src/main/java/com/mbooking/config/WebSecurityConfig.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.component.html
  frontend/src/app/components/manage-admins/manage-admins.component.css
  frontend/src/app/components/manage-admins/manage-admins.component.html
  frontend/src/app/components/manage-users/manage-users.component.css
  frontend/src/app/components/manifestation/manifestation.component.html
  frontend/src/app/components/manifestation/manifestation.component.ts
  frontend/src/app/components/open-space-layout/open-space-layout.component.html
  frontend/src/app/components/open-space-layout/open-space-layout.component.ts
  frontend/src/app/components/pagination/pagination.component.html
  frontend/src/app/components/seating-section/seating-section.component.ts
  frontend/src/app/components/stadium-layout/stadium-layout.component.html
  frontend/src/app/components/stadium-layout/stadium-layout.component.ts
  frontend/src/app/components/standing-section/standing-section.component.ts
  frontend/src/app/components/theater-layout/theater-layout.component.html
  frontend/src/app/components/theater-layout/theater-layout.component.ts
  frontend/src/app/services/utility.service.ts
  frontend/src/tsconfig.json
Labels: bug, enhancement

#93 Manage manifestation sections
  backend/code/m-booking/src/main/java/com/mbooking/controller/ReservationController.java
  backend/code/m-booking/src/main/java/com/mbooking/dto/LocationDTO.java
  backend/code/m-booking/src/main/java/com/mbooking/dto/ManifestationDTO.java
  backend/code/m-booking/src/main/java/com/mbooking/dto/ManifestationSectionDTO.java
  backend/code/m-booking/src/main/java/com/mbooking/model/Manifestation.java
  backend/code/m-booking/src/main/java/com/mbooking/model/ManifestationSection.java
  backend/code/m-booking/src/main/java/com/mbooking/service/impl/ManifestationServiceImpl.java
  backend/code/m-booking/src/main/java/com/mbooking/service/impl/ReservationServiceImpl.java
  backend/code/m-booking/src/main/resources/import_data.sql
  backend/code/m-booking/src/test/java/com/mbooking/controller/ManifestationControllerIntegrationTests.java
  backend/code/m-booking/src/test/java/com/mbooking/service/ManifestationServiceIntegrationTests.java
  backend/code/m-booking/src/test/java/com/mbooking/service/ManifestationServiceUnitTests.java
  frontend/src/app/app.module.ts
  frontend/src/app/components/home/home.module.ts
  frontend/src/app/components/layout-sections/layout.sections.module.ts
  frontend/src/app/components/layout-sections/open-space-layout/open-space-layout.component.css
  frontend/src/app/components/layout-sections/open-space-layout/open-space-layout.component.html
  frontend/src/app/components/layout-sections/open-space-layout/open-space-layout.component.spec.ts
  frontend/src/app/components/layout-sections/open-space-layout/open-space-layout.component.ts
  frontend/src/app/components/layout-sections/seating-section/seating-section.component.css
  frontend/src/app/components/layout-sections/seating-section/seating-section.component.html
  frontend/src/app/components/layout-sections/seating-section/seating-section.component.spec.ts
  frontend/src/app/components/layout-sections/seating-section/seating-section.component.ts
  frontend/src/app/components/layout-sections/stadium-layout/stadium-layout.component.css
  frontend/src/app/components/layout-sections/stadium-layout/stadium-layout.component.html
  frontend/src/app/components/layout-sections/stadium-layout/stadium-layout.component.spec.ts
  frontend/src/app/components/layout-sections/stadium-layout/stadium-layout.component.ts
  frontend/src/app/components/layout-sections/standing-section/standing-section.component.css
  frontend/src/app/components/layout-sections/standing-section/standing-section.component.html
  frontend/src/app/components/layout-sections/standing-section/standing-section.component.spec.ts
  frontend/src/app/components/layout-sections/standing-section/standing-section.component.ts
  frontend/src/app/components/layout-sections/theater-layout/theater-layout.component.css
  frontend/src/app/components/layout-sections/theater-layout/theater-layout.component.html
  frontend/src/app/components/layout-sections/theater-layout/theater-layout.component.spec.ts
  frontend/src/app/components/layout-sections/theater-layout/theater-layout.component.ts
  frontend/src/app/components/manage-manifestation/manage-manifestation-days/manage-manifestation-days.component.css
  frontend/src/app/components/manage-manifestation/manage-manifestation-sections/manage-manifestation-sections.component.html
  frontend/src/app/components/manage-manifestation/manage-manifestation-sections/manage-manifestation-sections.component.ts
  frontend/src/app/components/manage-manifestation/manage-manifestation.component.css
  frontend/src/app/components/manage-manifestation/manage-manifestation.component.html
  frontend/src/app/components/manage-manifestation/manage-manifestation.component.ts
  frontend/src/app/components/manage-manifestation/manage-manifestation.module.ts
  frontend/src/app/components/manifestation/manifestation.component.ts
  frontend/src/app/components/manifestations/manifestations.component.ts
  frontend/src/app/components/manifestations/manifestations.module.ts
  frontend/src/app/components/seating-section/seating-section.component.css
  frontend/src/app/models/location.model.ts
  frontend/src/app/services/location.service.ts
  frontend/src/app/services/section.service.spec.ts
  frontend/src/app/services/section.service.ts
Labels: bug, enhancement

#96 Front search and bug fixes
  backend/code/m-booking/pom.xml
  backend/code/m-booking/src/main/java/com/mbooking/exception/ReservationCannotBeCanceledException.java
  backend/code/m-booking/src/main/java/com/mbooking/model/ManifestationImage.java
  backend/code/m-booking/src/main/java/com/mbooking/service/impl/ReservationServiceImpl.java
  backend/code/m-booking/src/main/resources/import_data.sql
  backend/code/m-booking/src/test/java/com/mbooking/service/ReservationServiceIntegrationTests.java
  backend/code/m-booking/src/test/java/com/mbooking/service/ReservationServiceUnitTests.java
  backend/code/m-booking/src/test/resources/reservation_test_data.sql
  frontend/src/app/app.component.html
  frontend/src/app/app.module.ts
  frontend/src/app/components/home/home.component.html
  frontend/src/app/components/home/home.component.ts
  frontend/src/app/components/manifestation/manifestation.component.css
  frontend/src/app/components/manifestation/manifestation.component.html
  frontend/src/app/components/manifestation/manifestation.component.ts
  frontend/src/app/components/manifestations/manifestation-item/manifestation-item.component.html
  frontend/src/app/components/manifestations/manifestation-item/manifestation-item.component.ts
  frontend/src/app/components/manifestations/manifestations.component.css
  frontend/src/app/components/manifestations/manifestations.component.html
  frontend/src/app/components/manifestations/manifestations.component.ts
  frontend/src/app/services/manifestation.service.ts
  frontend/src/styles.css
Labels: enhancement, test

#97 Front bug fixes
  frontend/src/app/app.component.html
  frontend/src/app/app.component.ts
  frontend/src/app/app.module.ts
  frontend/src/app/components/home/home.component.ts
  frontend/src/app/components/manifestation/manifestation.component.html
  frontend/src/app/components/manifestations/manifestations.module.ts
  frontend/src/app/services/authentication.service.ts
Labels: bug

#98 Front lint fixes
  backend/code/m-booking/src/main/java/com/mbooking/exception/FileUploadExceptionHandler.java
  backend/code/m-booking/src/main/resources/application.properties
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.component.html
  frontend/src/app/app.module.ts
  frontend/src/app/components/layout-sections/stadium-layout/stadium-layout.component.ts
  frontend/src/app/components/layout-sections/standing-section/standing-section.component.ts
  frontend/src/app/components/login/login.component.css
  frontend/src/app/components/manage-manifestation/manage-manifestation-days/manage-manifestation-days.component.ts
  frontend/src/app/components/manage-manifestation/manage-manifestation-images/manage-manifestation-images.component.ts
  frontend/src/app/components/manage-manifestation/manage-manifestation-sections/manage-manifestation-sections.component.ts
  frontend/src/app/components/manage-manifestation/manage-manifestation.component.css
  frontend/src/app/components/manage-manifestation/manage-manifestation.component.html
  frontend/src/app/components/manage-manifestation/manage-manifestation.component.ts
  frontend/src/app/components/manage-manifestation/manage-manifestation.module.ts
  frontend/src/app/components/manifestation/manifestation.component.ts
  frontend/src/app/components/manifestations/manifestation-item/manifestation-item.component.css
  frontend/src/app/components/manifestations/manifestation-item/manifestation-item.component.html
  frontend/src/app/components/manifestations/manifestation-item/manifestation-item.component.spec.ts
  frontend/src/app/components/manifestations/manifestation-item/manifestation-item.component.ts
  frontend/src/app/components/manifestations/manifestations.component.ts
  frontend/src/app/components/manifestations/manifestations.module.ts
  frontend/src/app/components/profile/profile.component.css
  frontend/src/app/components/register/register.component.css
  frontend/src/app/guards/role.guard.ts
  frontend/src/app/models/authority.ts
  frontend/src/app/models/layout.ts
  frontend/src/app/models/location.model.ts
  frontend/src/app/models/manifestation-image-model.ts
  frontend/src/app/models/manifestation-section.model.ts
  frontend/src/app/models/manifestation.model.ts
  frontend/src/app/models/profile-edit-info.model.ts
  frontend/src/app/models/reservation-details.ts
  frontend/src/app/models/results.ts
  frontend/src/app/models/section.ts
  frontend/src/app/services/alert.service.ts
  frontend/src/app/services/layout.service.ts
  frontend/src/app/services/location.service.ts
  frontend/src/app/services/manifestation.service.ts
  frontend/src/app/services/toaster.service.ts
  frontend/src/app/services/utility.service.ts
  frontend/src/app/validators/manifestation.validator.ts
  frontend/src/environments/environment.ts
Labels: enhancement

#99 Front manage locations
  backend/code/m-booking/src/main/java/com/mbooking/controller/LayoutController.java
  backend/code/m-booking/src/main/java/com/mbooking/controller/LocationController.java
  backend/code/m-booking/src/main/java/com/mbooking/controller/PaymentController.java
  backend/code/m-booking/src/main/java/com/mbooking/dto/LocationDTO.java
  backend/code/m-booking/src/main/java/com/mbooking/model/Location.java
  backend/code/m-booking/src/main/java/com/mbooking/repository/LocationRepository.java
  backend/code/m-booking/src/main/java/com/mbooking/service/LayoutService.java
  backend/code/m-booking/src/main/java/com/mbooking/service/LocationService.java
  backend/code/m-booking/src/main/java/com/mbooking/service/impl/LayoutServiceImpl.java
  backend/code/m-booking/src/main/java/com/mbooking/service/impl/LocationServiceImpl.java
  backend/code/m-booking/src/main/resources/application.properties
  backend/code/m-booking/src/test/java/com/mbooking/repository/LocationRepositoryIntegrationTest.java
  backend/code/m-booking/src/test/java/com/mbooking/service/LocationServiceIntegrationTest.java
  backend/code/m-booking/src/test/java/com/mbooking/service/LocationServiceUnitTest.java
  backend/code/m-booking/src/test/resources/import_data_h2.sql
  frontend/src/app/.gitignore
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.component.html
  frontend/src/app/app.module.ts
  frontend/src/app/components/create-location/create-location.component.css
  frontend/src/app/components/create-location/create-location.component.html
  frontend/src/app/components/create-location/create-location.component.spec.ts
  frontend/src/app/components/create-location/create-location.component.ts
  frontend/src/app/components/login/login.component.css
  frontend/src/app/components/manage-locations/manage-locations.component.css
  frontend/src/app/components/manage-locations/manage-locations.component.html
  frontend/src/app/components/manage-locations/manage-locations.component.spec.ts
  frontend/src/app/components/manage-locations/manage-locations.component.ts
  frontend/src/app/components/manage-manifestation/manage-manifestation-sections/manage-manifestation-sections.component.ts
  frontend/src/app/components/pagination/pagination.component.css
  frontend/src/app/components/pagination/pagination.component.html
  frontend/src/app/components/update-location/update-location.component.css
  frontend/src/app/components/update-location/update-location.component.html
  frontend/src/app/components/update-location/update-location.component.spec.ts
  frontend/src/app/components/update-location/update-location.component.ts
  frontend/src/app/models/location.model.ts
  frontend/src/app/services/layout.service.ts
  frontend/src/app/services/location.service.ts
Labels: enhancement

#102 Front reports
  backend/code/m-booking/src/main/java/com/mbooking/dto/reports/ReportDTO.java
  backend/code/m-booking/src/main/resources/application.properties
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/components/reports/reports.component.css
  frontend/src/app/components/reports/reports.component.html
  frontend/src/app/components/reports/reports.component.ts
  frontend/src/app/models/location-report.model.ts
  frontend/src/app/models/report.model.ts
  frontend/src/app/services/location.service.ts
  frontend/src/app/services/manifestation.service.ts
Labels: good first issue, help wanted

#105 Front pagination
  backend/code/m-booking/src/main/java/com/mbooking/selenium/ManageManifestationPage.java
  backend/code/m-booking/src/main/resources/application.properties
  backend/code/m-booking/src/main/resources/import_data.sql
  backend/code/m-booking/src/test/java/com/mbooking/controller/ManifestationControllerIntegrationTests.java
  backend/code/m-booking/src/test/java/com/mbooking/selenium/ManageManifestationPageTest.java
  backend/code/m-booking/src/test/java/com/mbooking/service/ManifestationServiceIntegrationTests.java
  frontend/src/app/components/manage-manifestation/manage-manifestation-days/manage-manifestation-days.component.css
  frontend/src/app/components/manage-manifestation/manage-manifestation-images/manage-manifestation-images.component.css
  frontend/src/app/components/manage-manifestation/manage-manifestation.component.css
  frontend/src/app/components/manage-manifestation/manage-manifestation.component.html
  frontend/src/app/components/manage-manifestation/manage-manifestation.component.ts
  frontend/src/app/components/manage-manifestation/manage-manifestation.module.ts
Labels: enhancement
