Repository leonidas97/kts-nwt, pull requests merged in 2020-01, with the labels that each got.

#70 Manifest controller tests
  backend/code/m-booking/src/main/java/com/mbooking/config/WebSecurityConfig.java
  backend/code/m-booking/src/main/java/com/mbooking/controller/ManifestationController.java
  backend/code/m-booking/src/main/java/com/mbooking/dto/ManifestationDTO.java
  backend/code/m-booking/src/main/java/com/mbooking/dto/ManifestationSectionDTO.java
  backend/code/m-booking/src/main/java/com/mbooking/model/Manifestation.java
  backend/code/m-booking/src/main/java/com/mbooking/service/impl/ManifestationServiceImpl.java
  backend/code/m-booking/src/test/java/com/mbooking/controller/ManifestationControllerIntegrationTests.java
  backend/code/m-booking/src/test/java/com/mbooking/service/ManifestationServiceIntegrationTests.java
  backend/code/m-booking/src/test/java/com/mbooking/service/ManifestationServiceUnitTests.java
  backend/code/m-booking/src/test/java/com/mbooking/suites/ManifestationTestSuite.java
  backend/code/m-booking/src/test/resources/import_data_h2.sql
Labels: test

#67 Reservation tests
  backend/code/m-booking/src/main/java/com/mbooking/config/ScheduledConfig.java
  backend/code/m-booking/src/main/java/com/mbooking/config/WebSecurityConfig.java
  backend/code/m-booking/src/main/java/com/mbooking/controller/ReservationController.java
  backend/code/m-booking/src/main/java/com/mbooking/dto/MakeReservationResponseDTO.java
  backend/code/m-booking/src/main/java/com/mbooking/exception/DuplicateSeatsException.java
  backend/code/m-booking/src/main/java/com/mbooking/exception/EmptyReservationDetailsException.java
  backend/code/m-booking/src/main/java/com/mbooking/exception/ManifestationReservationsAvailableException.java
  backend/code/m-booking/src/main/java/com/mbooking/exception/MaxReservationsException.java
  backend/code/m-booking/src/main/java/com/mbooking/exception/NoMoreSpaceException.java
  backend/code/m-booking/src/main/java/com/mbooking/exception/NoSuchManifestationDayException.java
  backend/code/m-booking/src/main/java/com/mbooking/exception/NoSuchManifestationException.java
  backend/code/m-booking/src/main/java/com/mbooking/exception/NoSuchReservationException.java
  backend/code/m-booking/src/main/java/com/mbooking/exception/NoSuchSeatException.java
  backend/code/m-booking/src/main/java/com/mbooking/exception/NoSuchSectionException.java
  backend/code/m-booking/src/main/java/com/mbooking/exception/NoSuchUserException.java
  backend/code/m-booking/src/main/java/com/mbooking/exception/ReservableUntilException.java
  backend/code/m-booking/src/main/java/com/mbooking/exception/ReservationNotFromCurrentCustomerException.java
  backend/code/m-booking/src/main/java/com/mbooking/exception/SeatTakenException.java
  backend/code/m-booking/src/main/java/com/mbooking/exception/SectionNotFromSameManifestationException.java
  backend/code/m-booking/src/main/java/com/mbooking/model/Customer.java
  backend/code/m-booking/src/main/java/com/mbooking/model/Reservation.java
  backend/code/m-booking/src/main/java/com/mbooking/model/ReservationDetails.java
  backend/code/m-booking/src/main/java/com/mbooking/repository/ReservationDetailsRepository.java
  backend/code/m-booking/src/main/java/com/mbooking/repository/ReservationRepository.java
  backend/code/m-booking/src/main/java/com/mbooking/service/ReservationService.java
  backend/code/m-booking/src/main/java/com/mbooking/service/impl/ReservationServiceImpl.java
  backend/code/m-booking/src/main/resources/application.properties
  backend/code/m-booking/src/main/resources/import_data.sql
  backend/code/m-booking/src/test/java/com/mbooking/controller/ReservationControllerIntegrationTests.java
  backend/code/m-booking/src/test/java/com/mbooking/repository/ReservationDetailsRepositoryIntegrationTests.java
  backend/code/m-booking/src/test/java/com/mbooking/repository/ReservationRepositoryIntegrationTests.java
  backend/code/m-booking/src/test/java/com/mbooking/service/ReservationServiceIntegrationTests.java
  backend/code/m-booking/src/test/java/com/mbooking/service/ReservationServiceUnitTests.java
  backend/code/m-booking/src/test/java/com/mbooking/utils/DatabaseHelper.java
  backend/code/m-booking/src/test/resources/application-test_reservation.properties
  backend/code/m-booking/src/test/resources/reservation_test_data.sql
Labels: enhancement, test

#72 Front manage manifests update
  backend/code/m-booking/src/main/java/com/mbooking/dto/ManifestationDTO.java
  backend/code/m-booking/src/main/java/com/mbooking/exception/ValidationExceptionHandler.java
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.component.css
  frontend/src/app/app.component.html
  frontend/src/app/app.module.ts
  frontend/src/app/components/manage-manifestation-days/manage-manifestation-days.component.css
  frontend/src/app/components/manage-manifestation-days/manage-manifestation-days.component.html
  frontend/src/app/components/manage-manifestation-days/manage-manifestation-days.component.spec.ts
  frontend/src/app/components/manage-manifestation-days/manage-manifestation-days.component.ts
  frontend/src/app/components/manage-manifestation-sections/manage-manifestation-sections.component.css
  frontend/src/app/components/manage-manifestation-sections/manage-manifestation-sections.component.html
  frontend/src/app/components/manage-manifestation-sections/manage-manifestation-sections.component.spec.ts
  frontend/src/app/components/manage-manifestation-sections/manage-manifestation-sections.component.ts
  frontend/src/app/components/manage-manifestation/manage-manifestation.component.css
  frontend/src/app/components/manage-manifestation/manage-manifestation.component.html
  frontend/src/app/components/manage-manifestation/manage-manifestation.component.ts
  frontend/src/app/components/manage-manifestation/manage-manifestation.module.ts
  frontend/src/app/models/manifestation.model.ts
  frontend/src/app/services/manifestation.service.ts
  frontend/src/app/services/toaster.service.ts
  frontend/src/app/validators/manifestation.validator.ts
  frontend/src/environments/environment.ts
  frontend/src/styles.css
  frontend/tsconfig.app.json
Labels: enhancement

#73 Small preview of manifestations
  backend/code/m-booking/src/main/resources/application.properties
  backend/code/m-booking/src/test/java/com/mbooking/controller/ReservationControllerIntegrationTests.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.component.css
  frontend/src/app/app.component.ts
  frontend/src/app/app.module.ts
  frontend/src/app/components/home/home.component.html
  frontend/src/app/components/home/home.component.ts
  frontend/src/app/components/manifestation/manifestation.component.css
  frontend/src/app/components/manifestation/manifestation.component.html
  frontend/src/app/components/manifestation/manifestation.component.spec.ts
  frontend/src/app/components/manifestation/manifestation.component.ts
  frontend/src/app/components/manifestations/manifestation-item/manifestation-item.component.css
  frontend/src/app/components/manifestations/manifestation-item/manifestation-item.component.html
  frontend/src/app/components/manifestations/manifestation-item/manifestation-item.component.spec.ts
  frontend/src/app/components/manifestations/manifestation-item/manifestation-item.component.ts
  frontend/src/app/components/manifestations/manifestations.component.css
  frontend/src/app/components/manifestations/manifestations.component.html
  frontend/src/app/components/manifestations/manifestations.component.spec.ts
  frontend/src/app/components/manifestations/manifestations.component.ts
  frontend/src/app/components/register/register.component.ts
  frontend/src/app/components/seating-section/seating-section.component.css
  frontend/src/app/components/seating-section/seating-section.component.html
  frontend/src/app/components/seating-section/seating-section.component.spec.ts
  frontend/src/app/components/seating-section/seating-section.component.ts
  frontend/src/app/components/stadium-layout/stadium-layout.component.css
  frontend/src/app/components/stadium-layout/stadium-layout.component.html
  frontend/src/app/components/stadium-layout/stadium-layout.component.spec.ts
  frontend/src/app/components/stadium-layout/stadium-layout.component.ts
  frontend/src/app/components/standing-section/standing-section.component.css
  frontend/src/app/components/standing-section/standing-section.component.html
  frontend/src/app/components/standing-section/standing-section.component.spec.ts
  frontend/src/app/components/standing-section/standing-section.component.ts
  frontend/src/app/services/manifestation.service.ts
  frontend/src/app/services/utility.service.spec.ts
  frontend/src/app/services/utility.service.ts
  frontend/src/styles.css
Labels: enhancement

#65 Authentication tests
  backend/code/m-booking/src/main/java/com/mbooking/config/WebSecurityConfig.java
  backend/code/m-booking/src/main/java/com/mbooking/dto/ChangePasswordRequestDTO.java
  backend/code/m-booking/src/main/java/com/mbooking/security/impl/AuthenticationServiceImpl.java
  backend/code/m-booking/src/main/java/com/mbooking/service/impl/LocationServiceImpl.java
  backend/code/m-booking/src/test/java/com/mbooking/controller/AuthenticationControllerIntegrationTest.java
  backend/code/m-booking/src/test/java/com/mbooking/controller/LocationControllerIntegrationTest.java
  backend/code/m-booking/src/test/java/com/mbooking/controller/ReservationControllerIntegrationTests.java
  backend/code/m-booking/src/test/java/com/mbooking/repository/CustomerRepositoryIntegrationTest.java
  backend/code/m-booking/src/test/java/com/mbooking/repository/LocationRepositoryIntegrationTest.java
  backend/code/m-booking/src/test/java/com/mbooking/service/AuthenticationServiceIntegrationTest.java
  backend/code/m-booking/src/test/java/com/mbooking/service/AuthenticationServiceUnitTest.java
  backend/code/m-booking/src/test/java/com/mbooking/service/LocationServiceIntegrationTest.java
  backend/code/m-booking/src/test/java/com/mbooking/service/LocationServiceUnitTest.java
  backend/code/m-booking/src/test/java/com/mbooking/suites/LocationTestSuite.java
  backend/code/m-booking/src/test/java/com/mbooking/utils/DatabaseHelper.java
  backend/code/m-booking/src/test/resources/application-test_h2.properties
  backend/code/m-booking/src/test/resources/application-test_unit.properties
Labels: bug, test

#77 Backend layout features
  backend/code/m-booking/src/main/java/com/mbooking/controller/LayoutController.java
  backend/code/m-booking/src/main/java/com/mbooking/dto/LayoutDTO.java
  backend/code/m-booking/src/main/java/com/mbooking/dto/SectionDTO.java
  backend/code/m-booking/src/main/java/com/mbooking/model/Layout.java
  backend/code/m-booking/src/main/java/com/mbooking/model/Section.java
  backend/code/m-booking/src/main/java/com/mbooking/repository/LayoutRepository.java
  backend/code/m-booking/src/main/java/com/mbooking/service/LayoutService.java
  backend/code/m-booking/src/main/java/com/mbooking/service/impl/LayoutServiceImpl.java
Labels: enhancement

#80 Front back fixes
  backend/code/m-booking/pom.xml
  backend/code/m-booking/src/main/java/com/mbooking/controller/ManifestationController.java
  backend/code/m-booking/src/main/java/com/mbooking/controller/PaymentController.java
  backend/code/m-booking/src/main/java/com/mbooking/dto/ManifestationDTO.java
  backend/code/m-booking/src/main/java/com/mbooking/exception/ApiExceptionHandler.java
  backend/code/m-booking/src/main/java/com/mbooking/model/ManifestationDay.java
  backend/code/m-booking/src/main/java/com/mbooking/repository/ManifestationDayRepository.java
  backend/code/m-booking/src/main/java/com/mbooking/repository/ManifestationRepository.java
  backend/code/m-booking/src/main/java/com/mbooking/service/ManifestationService.java
  backend/code/m-booking/src/main/java/com/mbooking/service/impl/ManifestationServiceImpl.java
  backend/code/m-booking/src/main/java/com/mbooking/utility/ManifestationDateComparator.java
  backend/code/m-booking/src/main/resources/application.properties
  backend/code/m-booking/src/main/resources/import_data.sql
  backend/code/m-booking/src/test/java/com/mbooking/controller/ManifestationControllerIntegrationTests.java
  backend/code/m-booking/src/test/java/com/mbooking/repository/ManifestationRepositoryIntegrationTests.java
  backend/code/m-booking/src/test/java/com/mbooking/service/ManifestationServiceIntegrationTests.java
  backend/code/m-booking/src/test/java/com/mbooking/service/ManifestationServiceUnitTests.java
  backend/code/m-booking/src/test/resources/import_data_h2.sql
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.component.css
  frontend/src/app/components/manage-manifestation/manage-manifestation-days/manage-manifestation-days.component.css
  frontend/src/app/components/manage-manifestation/manage-manifestation-days/manage-manifestation-days.component.html
  frontend/src/app/components/manage-manifestation/manage-manifestation-days/manage-manifestation-days.component.spec.ts
  frontend/src/app/components/manage-manifestation/manage-manifestation-days/manage-manifestation-days.component.ts
  frontend/src/app/components/manage-manifestation/manage-manifestation-sections/manage-manifestation-sections.component.css
  frontend/src/app/components/manage-manifestation/manage-manifestation-sections/manage-manifestation-sections.component.html
  frontend/src/app/components/manage-manifestation/manage-manifestation-sections/manage-manifestation-sections.component.spec.ts
  frontend/src/app/components/manage-manifestation/manage-manifestation-sections/manage-manifestation-sections.component.ts
  frontend/src/app/components/manage-manifestation/manage-manifestation.component.html
  frontend/src/app/components/manage-manifestation/manage-manifestation.component.ts
  frontend/src/app/components/manage-manifestation/manage-manifestation.module.ts
  frontend/src/app/models/manifestation.model.ts
Labels: enhancement

#85 Image upload
  backend/code/m-booking/src/main/java/com/mbooking/controller/ManifestationController.java
  backend/code/m-booking/src/main/java/com/mbooking/dto/ManifestationDTO.java
  backend/code/m-booking/src/main/java/com/mbooking/dto/ManifestationImageDTO.java
  backend/code/m-booking/src/main/java/com/mbooking/exception/FileUploadExceptionHandler.java
  backend/code/m-booking/src/main/java/com/mbooking/model/Manifestation.java
  backend/code/m-booking/src/main/java/com/mbooking/model/ManifestationImage.java
  backend/code/m-booking/src/main/java/com/mbooking/repository/ManifestationImageRepository.java
  backend/code/m-booking/src/main/java/com/mbooking/service/ManifestationService.java
  backend/code/m-booking/src/main/java/com/mbooking/service/impl/ManifestationServiceImpl.java
  backend/code/m-booking/src/main/java/com/mbooking/utility/Constants.java
  backend/code/m-booking/src/main/resources/application.properties
  frontend/src/app/components/manage-manifestation/manage-manifestation-images/manage-manifestation-images.component.css
  frontend/src/app/components/manage-manifestation/manage-manifestation-images/manage-manifestation-images.component.html
  frontend/src/app/components/manage-manifestation/manage-manifestation-images/manage-manifestation-images.component.spec.ts
  frontend/src/app/components/manage-manifestation/manage-manifestation-images/manage-manifestation-images.component.ts
  frontend/src/app/components/manage-manifestation/manage-manifestation.component.css
  frontend/src/app/components/manage-manifestation/manage-manifestation.component.html
  frontend/src/app/components/manage-manifestation/manage-manifestation.component.ts
  frontend/src/app/components/manage-manifestation/manage-manifestation.module.ts
  frontend/src/app/models/manifestation-image-model.ts
  frontend/src/app/models/manifestation.model.ts
  frontend/src/app/services/manifestation.service.ts
  frontend/src/app/services/toaster.service.ts
  frontend/src/environments/environment.ts
Labels: enhancement

#89 Added access to manifestation management for the regular admin
  frontend/src/app/app.component.html
  frontend/src/app/components/manifestations/manifestation-item/manifestation-item.component.html
  frontend/src/app/components/manifestations/manifestation-item/manifestation-item.component.ts
Labels: good first issue
